"use strict";
(()=>{
const $=id=>document.getElementById(id),data=window.BL_PORTAL_CONTENT||{articles:[]};
const articles=data.articles||[],out=$("radar-results"),filters=$("radar-filters");
const categories=[["SVE","all"],["ANDROID / UREĐAJI","devices"],["AI / SOFTVER","software"],["SIGURNOST","security"],["STVARALAŠTVO","create"],["VIJESTI","news"]];
const keys={devices:["Uređaji","Audio"],software:["AI","Softver"],security:["Sigurnost"],create:["Projekti"],news:[]};
const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const storeKey="bl-tech-saved-v1";let saved=[];
try{const input=JSON.parse(localStorage.getItem(storeKey)||"[]");if(Array.isArray(input))saved=input.filter(id=>articles.some(a=>a.id===id));}catch{}
function save(){try{localStorage.setItem(storeKey,JSON.stringify(saved));}catch{}}
function btnArticle(a){const button=make("button","radar-save",saved.includes(a.id)?"SAČUVANO ✓":"SAČUVAJ +");button.type="button";button.setAttribute("aria-pressed",String(saved.includes(a.id)));button.addEventListener("click",()=>{saved=saved.includes(a.id)?saved.filter(id=>id!==a.id):[...saved,a.id];save();renderRadar();renderSaved();});return button;}
function story(a){const card=make("article","radar-card");const label=make("span","p-label",a.category+" / AUTORSKI VODIČ");const h=make("h3","",a.title),p=make("p","",a.summary),link=make("a","radar-card-link","PROČITAJ ↗");link.href=a.href;card.append(label,h,p,link,btnArticle(a));return card;}
let active="all";
const news=()=>Array.isArray(window.BL_TECH_PULSE)?window.BL_TECH_PULSE.filter(x=>x.kind==="vanjski"&&typeof x.title==="string"&&typeof x.url==="string"&&/^https:\/\//.test(x.url)).slice(0,6):[];
function renderRadar(){out.replaceChildren();let current=active==="all"?articles:articles.filter(a=>(keys[active]||[]).includes(a.category));if(active==="news"){const items=news();for(const item of items){const a=make("a","radar-card radar-news");a.href=item.url;a.target="_blank";a.rel="noopener noreferrer";a.append(make("span","p-label",item.source+" / VANJSKI IZVOR"),make("h3","",item.title),make("p","",item.date||"Datum nije naveden"),make("span","radar-card-link","IZVOR ↗"));out.append(a);}if(!items.length)out.append(make("p","dim","Nema dostupnih vijesti. Pogledaj listu izvora u TECH zoni."));return;}for(const a of current)out.append(story(a));if(!current.length)out.append(make("p","dim","Za ovu temu trenutno nema objavljenih autorskih tekstova."));}
categories.forEach(([label,id])=>{const b=make("button","radar-filter",label);b.type="button";b.setAttribute("aria-pressed",String(id===active));b.addEventListener("click",()=>{active=id;for(const c of filters.children)c.setAttribute("aria-pressed",String(c===b));renderRadar();});filters.append(b);});renderRadar();
function renderSaved(){const target=$("saved-list");target.replaceChildren();const found=articles.filter(a=>saved.includes(a.id));if(!found.length)target.append(make("p","dim","Još nisi sačuvao članak. Izaberi temu na Radaru i pritisni SAČUVAJ +."));for(const a of found)target.append(story(a));}
$("saved-clear").addEventListener("click",()=>{saved=[];save();renderRadar();renderSaved();});renderSaved();
window.addEventListener("bl-news-updated",()=>{if(active==="news")renderRadar();});
const facts=[
{title:"Web je nastao u CERN-u",description:"Tim Berners-Lee predložio je World Wide Web 1989. godine tokom rada u CERN-u.",source:"CERN",url:"https://home.cern/science/computing/birth-web"},
{title:"QR kod je razvijen 1994.",description:"DENSO WAVE je 1994. razvio QR kod kako bi se informacije brže očitavale.",source:"DENSO WAVE",url:"https://www.qrcode.com/en/history/"},
{title:"HTTPS štiti prenos podataka",description:"HTTPS koristi TLS za zaštitu komunikacije između preglednika i web servera. Ne garantuje da je svaka stranica pouzdana.",source:"MDN Web Docs",url:"https://developer.mozilla.org/en-US/docs/Glossary/HTTPS"}
];let factIndex=Math.floor(Date.now()/86400000)%facts.length;
function fact(){const x=facts[factIndex];$("fact-index").textContent="PROVJERENA ČINJENICA / "+String(factIndex+1).padStart(2,"0");$("fact-title").textContent=x.title;$("fact-description").textContent=x.description;$("fact-source").href=x.url;$("fact-source").textContent=x.source+" ↗";}
$("fact-next").addEventListener("click",()=>{factIndex=(factIndex+1)%facts.length;fact();});fact();
const tools=[
{id:"units",title:"Pretvarač jedinica",desc:"Pretvori metre u centimetre, kilometre u metre ili kilograme u grame.",fields:[["value","Vrijednost",1],["unit","Odaberi pretvaranje",null,[["mcm","m → cm"],["kmm","km → m"],["kgg","kg → g"],["cmbm","cm → m"]]]],calc:v=>{const k={mcm:100,kmm:1000,kgg:1000,cmbm:.01},unit=v.unit;return {result:nf(v.value*k[unit])+" "+({mcm:"cm",kmm:"m",kgg:"g",cmbm:"m"}[unit]),note:"Pretvaranje bez zaokruživanja ulaznih vrijednosti."};}},
{id:"area",title:"Površina prostora",desc:"Izračunaj površinu pravougaonog poda ili zida u kvadratnim metrima.",fields:[["length","Dužina (m)",4],["width","Širina (m)",3]],calc:v=>({result:nf(v.length*v.width)+" m²",note:"Površina pravougaonika. Za složene oblike računaj dijelove odvojeno."})},
{id:"time",title:"Trajanje zadatka",desc:"Pretvori sate i minute rada u ukupan broj minuta.",fields:[["hours","Sati",2],["minutes","Minute",30]],calc:v=>({result:nf(Math.round(v.hours*60+v.minutes),0)+" minuta",note:"Zbroj sati i minuta; za naplatu je potreban dogovor o satnici."})},
{id:"price",title:"Kalkulator ponude",desc:"Izračunaj cijenu rada i materijala, prije poreza i drugih troškova.",fields:[["hours","Sati rada",5],["rate","Satnica (KM)",20],["materials","Materijal (KM)",45]],calc:v=>({result:nf(v.hours*v.rate+v.materials)+" KM",note:"Osnovni zbir rada i materijala. Ne uključuje porez, prevoz ni ostale troškove."})},
{id:"size",title:"Veličina datoteke",desc:"Pretvori megabajte (MB) u kilobajte (KB) koristeći decimalne SI jedinice.",fields:[["megabytes","Veličina (MB)",12.5]],calc:v=>({result:nf(v.megabytes*1000)+" KB",note:"Decimalno: 1 MB = 1000 KB. Za binarne jedinice koriste se MiB i KiB."})}
];
const fmt=new Intl.NumberFormat("bs-BA",{maximumFractionDigits:3});const nf=(x,d)=>new Intl.NumberFormat("bs-BA",{maximumFractionDigits:d===undefined?3:d}).format(x);
let selected=tools[0],fields=$("lab-fields");
function renderLab(){const t=selected;$("lab-title").textContent=t.title;$("lab-description").textContent=t.desc;$("lab-output").textContent="—";$("lab-explanation").textContent="Unesi vrijednosti i izračunaj.";fields.replaceChildren();for(const [id,label,value,options] of t.fields){const box=make("label","lab-field"),caption=make("span","",label);let input;if(options){input=document.createElement("select");for(const [val,name] of options){const opt=document.createElement("option");opt.value=val;opt.textContent=name;input.append(opt);}}else{input=document.createElement("input");input.type="number";input.inputMode="decimal";input.step="any";input.min="0";input.max="10000000";input.required=true;input.value=String(value);}input.name=id;box.append(caption,input);fields.append(box);}}
for(const t of tools){const b=make("button","lab-tab",t.title);b.type="button";b.setAttribute("aria-pressed",String(t===selected));b.addEventListener("click",()=>{selected=t;for(const el of $("lab-tabs").children)el.setAttribute("aria-pressed",String(el===b));renderLab();});$("lab-tabs").append(b);}renderLab();
$("lab-form").addEventListener("submit",event=>{event.preventDefault();const values={};for(const field of fields.querySelectorAll("input,select")){if(field.tagName==="SELECT"){values[field.name]=field.value;continue;}const n=Number(field.value);if(!field.value.trim()||!Number.isFinite(n)||n<0||n>10000000){$("lab-output").textContent="Provjeri unos";$("lab-explanation").textContent="Unesi brojeve od 0 do 10.000.000 u sva obavezna polja.";return;}values[field.name]=n;}const result=selected.calc(values);$("lab-output").textContent=result.result;$("lab-explanation").textContent=result.note;});
})();